### ISSUE TITLE
config-install.plist 在哪里？

### ISSUE THREAD

**Issue by f1ynng8** [JackiePenghe/OC-EFI-ASUS-B250M-KYLIN#2]
安装过程中 请使用的config-install.plist《记得重新命名为config.plist》

但是没有找到config-install.plist在哪个位置？

**Comment by JackiePenghe** [comment]
没有就直接用试试，应该也能用。好像被我自己删了

**Comment by JackiePenghe** [comment]
> 安装过程中 请使用的config-install.plist《记得重新命名为config.plist》
> 
> 但是没有找到config-install.plist在哪个位置？

没有应该直接就能用的，readme已更新，版本也重新升级了一下，请根据需要下载你所需要的版本

**Comment by f1ynng8** [comment]
感谢大佬。
